# Generated by Django 6.0.7 on 2026-08-10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetodo_api", "0002_todo_schedule_history_and_recurrence"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="locationtraveltime",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="category",
            name="color_hex",
            field=models.CharField(
                default="#7c6ff7",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a six-digit hex color such as #7c6ff7.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="notes",
            field=models.TextField(blank=True, default="", max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="locationtraveltime",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=15,
                validators=[django.core.validators.MaxValueValidator(10080)],
            ),
        ),
        migrations.AlterField(
            model_name="repeatrule",
            name="interval",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Every N units",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="todoentry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="todos",
                to="timetodo_api.category",
            ),
        ),
        migrations.AlterField(
            model_name="todoentry",
            name="description",
            field=models.TextField(blank=True, default="", max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="todoentry",
            name="due_time",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a 24-hour time in HH:MM format.",
                        regex="^(?:[01]\\d|2[0-3]):[0-5]\\d$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="todoentry",
            name="original_planned_start_time",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a 24-hour time in HH:MM format.",
                        regex="^(?:[01]\\d|2[0-3]):[0-5]\\d$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="todoentry",
            name="planned_duration",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minutes",
                validators=[django.core.validators.MaxValueValidator(525600)],
            ),
        ),
        migrations.AlterField(
            model_name="todoentry",
            name="planned_start_time",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a 24-hour time in HH:MM format.",
                        regex="^(?:[01]\\d|2[0-3]):[0-5]\\d$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["owner", "name"], name="category_owner_name_idx"),
        ),
        migrations.AddIndex(
            model_name="repeatrule",
            index=models.Index(
                fields=["todo", "frequency"], name="repeat_todo_frequency_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timesession",
            index=models.Index(fields=["todo", "start"], name="session_todo_start_idx"),
        ),
        migrations.AddIndex(
            model_name="todoentry",
            index=models.Index(
                fields=["owner", "do_date", "planned_start_time"],
                name="todo_owner_schedule_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="todoentry",
            index=models.Index(
                fields=["owner", "status", "updated_at"],
                name="todo_owner_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationtraveltime",
            constraint=models.UniqueConstraint(
                fields=("owner", "location_key"), name="unique_owner_location_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationtraveltime",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__lte", 10080)),
                name="travel_duration_reasonable",
            ),
        ),
        migrations.AddConstraint(
            model_name="repeatrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1), ("interval__lte", 365)),
                name="repeat_interval_reasonable",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end__isnull", True),
                    ("end__gte", models.F("start")),
                    _connector="OR",
                ),
                name="session_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="todoentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_duration__lte", 525600)),
                name="todo_duration_reasonable",
            ),
        ),
    ]
